name: Build and Deploy to AWS Fargate

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        working-directory: ./devopshive-website
        run: npm ci

      - name: Build Next.js App
        working-directory: ./devopshive-website
        run: npm run build

      - name: Prepare Docker Build Context
        run: |
          mkdir docker-build
          cp -r ./devopshive-website/.next docker-build/
          cp -r ./devopshive-website/public docker-build/
          cp -r ./devopshive-website/node_modules docker-build/
          cp ./devopshive-website/package.json docker-build/
          cp ./devopshive-website/next.config.js docker-build/ || true

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      - name: Import ECR Repo
        run: terraform import aws_ecr_repository.app devopshive-website || true
        working-directory: ./terraform

      - name: Ensure ECR repository exists
        run: |
          aws ecr describe-repositories --repository-names devopshive-website || \
          aws ecr create-repository --repository-name devopshive-website
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-west-1

      - name: Apply Terraform
        working-directory: ./terraform
        run: |
          # Only import ECS service if it already exists
          if aws ecs describe-services --cluster devopshive-cluster --services devopshive-service --query "services[0].status" --output text 2>/dev/null | grep -q "ACTIVE"; then
            echo "Importing existing ECS service..."
            terraform import aws_ecs_service.app devopshive-cluster/devopshive-service || true
          fi

          terraform plan -out=tfplan
          terraform apply -auto-approve tfplan

      - name: Get Terraform Outputs
        id: tf_outputs
        run: |
          echo "ECS_CLUSTER=$(terraform output -raw ecs_cluster_name)" >> $GITHUB_ENV
          echo "ECR_URL=$(terraform output -raw ecr_repo_url)" >> $GITHUB_ENV
        working-directory: ./terraform

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push Docker Image to ECR
        run: |
          IMAGE_TAG=${GITHUB_SHA}
          # Build the Docker image
          docker build -t ${{ steps.login-ecr.outputs.registry }}/devopshive-website:$IMAGE_TAG -f ./devopshive-website/Dockerfile ./devopshive-website
          # Push the commit-specific tag
          docker push ${{ steps.login-ecr.outputs.registry }}/devopshive-website:$IMAGE_TAG
          # Tag as latest
          docker tag ${{ steps.login-ecr.outputs.registry }}/devopshive-website:$IMAGE_TAG ${{ steps.login-ecr.outputs.registry }}/devopshive-website:latest
          # Push latest tag
          docker push ${{ steps.login-ecr.outputs.registry }}/devopshive-website:latest
