name: Build and Dockerize Next.js App

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-dockerize:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: ./devopshive-website/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('devopshive-website/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        working-directory: ./devopshive-website
        run: npm ci

      - name: Build Next.js App
        working-directory: ./devopshive-website
        run: npm run build

      - name: Build Docker Image
        run: |
          docker build -t devopshive/website:${{ github.sha }} ./devopshive-website
